import { Card } from "@/types/card.type";

export const Cards: Array<Card> = [
  {
    id: 1,
    value: "6.950",
    shortName: "BTC",
    name: "Bitcoin",
    backgroundImage: "url('/imgs/b_1.svg')",
  },
  {
    id: 2,
    value: "6.950",
    shortName: "ANCH",
    name: "Avalanche",
    backgroundImage: "url('/imgs/b_2.svg')",
  },
  {
    id: 3,
    value: "6.950",
    shortName: "ETH",
    name: "Ethereum",
    backgroundImage: "url('/imgs/b_3.svg')",
  },
  {
    id: 4,
    value: "6.950",
    shortName: "USDT",
    name: "Tether",
    backgroundImage: "url('/imgs/b_4.svg')",
  },
  {
    id: 5,
    value: "6.950",
    shortName: "BNB",
    name: "BNB",
    backgroundImage: "url('/imgs/b_5.svg')",
  },
  {
    id: 6,
    value: "6.950",
    shortName: "XRP",
    name: "XRP",
    backgroundImage: "url('/imgs/b_6.svg')",
  },
  {
    id: 7,
    value: "6.950",
    shortName: "ADA",
    name: "Cardano",
    backgroundImage: "url('/imgs/b_7.svg')",
  },
  {
    id: 8,
    value: "6.950",
    shortName: "DoGE",
    name: "Dogecoin",
    backgroundImage: "url('/imgs/b_8.svg')",
  },
  {
    id: 9,
    value: "6.950",
    shortName: "MaTIC",
    name: "Polygon",
    backgroundImage: "url('/imgs/b_9.svg')",
  },
  {
    id: 10,
    value: "6.950",
    shortName: "SOL",
    name: "Solana",
    backgroundImage: "url('/imgs/b_10.svg')",
  },
  {
    id: 11,
    value: "6.950",
    shortName: "DOT",
    name: "Polkadot",
    backgroundImage: "url('/imgs/b_11.svg')",
  },
  {
    id: 12,
    value: "6.950",
    shortName: "TRX",
    name: "TRON",
    backgroundImage: "url('/imgs/b_12.svg')",
  },
  {
    id: 13,
    value: "6.950",
    shortName: "BUSD",
    name: "Binance USD",
    backgroundImage: "url('/imgs/b_13.svg')",
  },
  {
    id: 14,
    value: "6.950",
    shortName: "LTC",
    name: "Litecoin",
    backgroundImage: "url('/imgs/b_14.svg')",
  },
  {
    id: 15,
    value: "6.950",
    shortName: "SHIB",
    name: "Shiba Inu",
    backgroundImage: "url('/imgs/b_15.svg')",
  },
  {
    id: 16,
    value: "6.950",
    shortName: "KUBJ",
    name: "Chainlink",
    backgroundImage: "url('/imgs/b_16.svg')",
  },
];
